# .travis.yml

warnings_are_errors: false

os:
  - linux

language: r
r:
  - oldrel
  - release
  - devel

sudo: required

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap
  - sudo apt-get install libv8-dev
  - sudo apt-get install aptitude -y
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo aptitude install -y gdal-bin
  - sudo aptitude install -y libgdal1-dev
  - sudo aptitude install -y libproj-dev

repos:
  CRAN: https://cloud.r-project.org

r_packages:
  - rmarkdown

r_github_packages:
  - bcgov/rems

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change
