language: r
cache: packages
dist: trusty

before_install:
  - sudo apt-get install libv8-dev

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    rooms:
      - poissonconsulting:BKjfn7jsVh8zXTu2rq7BEQEb
    on_success: change
    on_failure: always
