language: r
cache: packages
dist: trusty

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    rooms:
      - poissonconsulting:BKjfn7jsVh8zXTu2rq7BEQEb
    on_success: change
    on_failure: always
