language: r
sudo: required
cache: packages

r:
  - release
#  - devel breaking on devel rgdal - Jan 2017

before_install:
  - sudo apt-get install libv8-dev
  - sudo apt-get install aptitude -y
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo aptitude install -y gdal-bin
  - sudo aptitude install -y libproj-dev

repos:
  CRAN: https://cloud.r-project.org

r_packages:
  - rgdal
  - rmarkdown

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    rooms:
      - poissonconsulting:BKjfn7jsVh8zXTu2rq7BEQEb
    on_success: change
    on_failure: always
